### ISSUE TITLE
Finished Project Source

### ISSUE THREAD

**Issue by aza0092** [psauthor/ModelsCourse#7]
I downloaded the zip folder for the project code for the course (https://app.pluralsight.com/library/courses/aspdotnet-core-bestpractices-models/), and it seems that the included project here is simply the starting point for the course. Would you share the finished project? Would help me and many learners a ton!

**Comment by shawnwildermuth** [comment]
The course has the full source code for download. It's not here in the Repo.

**Comment by aza0092** [comment]
It doesn't seem like it. I downloaded the exercise files on Pluralsight as well, and it has the same project as here on Github. Can you link me the finished project for the course?

**Comment by shawnwildermuth** [comment]
I can't link it for you, but I've contacted support and the Exercise Files should be available in the next day or two. I'll ping you here when it's fixed. Sorry for the confusion and limitations.

**Comment by shawnwildermuth** [comment]
If you re-download the exercise files, they are in there now. Sorry for the delay.
